org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric properties
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod properties
version=1.0.0
group=com.psychananaz.psymod

# Dependencies
fabric_api_version=0.158.0+26.2
modmenu_version=20.0.1